services:
  DevReactWebApp:
    image: localhost:5000/aspnet-react-dev-container
    container_name: devreactwebapp
    ports: 
      - "80:80"
      - "443:443"
    working_dir: /app
    volumes:
      - ../../ReactWebApp:/app
      - /home/pp/Repos/aspnet-practice/Certificates:/https:ro
    command: sh -c "dotnet build && dotnet watch run"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=QkpkmwUqymKdZLutWZIj
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet.pfx