# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

services:
  DevReactWebApp:
    image: localhost:5000/aspnet-react-dev-container
    container_name: devreactwebapp
    ports: 
      - "80:80"
      - "5000-5001:5000-5001"
    working_dir: /app
    volumes:
      - ../../ReactWebApp:/app
      - ~/.vsdbg:/remote_debugger:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000